---
- name: Disable current module
  shell: dnf module disable nodejs -y

- name: Enable the nodejs version 20
  shell: dnf module enable nodejs:20 -y

- name: Installing nodejs
  dnf:
    name: nodejs
    state: present

- name: Add application user
  user:
    name: expense

- name: Copy backend config file
  template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: import common role
  import_role:
    name: common
    tasks_from: App_req

- name: download .nodejs Dependencies
  community.general.npm:
    path: /app
    state: latest


- name: Install PyMySQL using pip
  pip:
    name:
      - pymysql
      - cryptography
    state: present

- name: Install MySQL Client
  dnf:
    name: mysql
    state: installed

# Import of sql script with encoding option
- name: Load sechma
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.awsdevops.sbs


- name: Start the backend service
  service:
    name: backend
    state: started
    enabled: yes
    daemon-reload: yes





