#SPDX-License-Identifier: MIT-0

  - name: install nginx
    dnf:
      name: nginx
      state: present

  - name: copy the conf file
    copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: import common role
    import_role:
      name: common
      tasks_from: App_req


  - name: Start the nginx service
    service:
      name: nginx
      state: started
      enabled: yes



